# Generated by Django 4.2.7 on 2023-11-06 21:39

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khneu_pub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='images/article/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('image', models.ImageField(upload_to='images/faculty/')),
            ],
        ),
        migrations.AddField(
            model_name='specialization',
            name='image',
            field=models.ImageField(default=None, upload_to='images/specialization/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialization',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slg', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khneu_pub_app.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khneu_pub_app.specialization'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='faculty',
            field=models.ForeignKey(default='122', on_delete=django.db.models.deletion.CASCADE, to='khneu_pub_app.faculty'),
            preserve_default=False,
        ),
    ]
