# Generated by Django 4.2.7 on 2023-11-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khneu_pub_app', '0009_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['pk']},
        ),
    ]
