# Generated by Django 4.2.7 on 2023-11-27 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('khneu_pub_app', '0012_alter_article_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
