# Generated by Django 4.2.7 on 2023-11-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khneu_pub_app', '0013_alter_article_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['pk']},
        ),
    ]
