# Generated by Django 4.2.7 on 2023-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khneu_pub_app', '0014_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='images/profile_photo/default_photo.png', upload_to='images/article/'),
        ),
    ]
